### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [anael-seghezzi/CToy#1]
Some parameters (like "[${MTCL_SOURCE_DIR}/3rdparty/glfw/include](https://github.com/anael-seghezzi/CToy/blob/e414586bbd14ff4d028f40dd5054b1f68eaa13df/CMakeLists.txt#L82)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](https://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by anael-seghezzi** [comment]
Good to know, I was not aware of that. Thanks.

**Comment by elfring** [comment]
Thanks for [your improvement of affected build scripts](https://github.com/anael-seghezzi/CToy/commit/4690573d91ac28fe0f60907be5ce8daaae99c50c#diff-af3b638bc2a3e6c650974192a53c7291L6).
