### ISSUE TITLE
Issue with my Linux port

### ISSUE THREAD

**Issue by Smilex** [anael-seghezzi/CToy#12]
It relies on a system installation of your fork of tcc. I get this error now that I've removed it - "tcc: error: file '/usr/local/lib/tcc/x86-64/libtcc1.a' not found"

I guess this is some RPATH thing. I did readelf -d, and the RPATH entry looks like this:
0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/]

libtcc1.a is correctly installed alongside the CToy executable.

I will fix this

**Comment by anael-seghezzi** [comment]
The thing is libtcc1.a is not the same thing as libtcc.a (libtcc library). It's only some small specific tcc-related runtime code. So first thing should be to build libtcc.so (dynamic library) with the correct rpath so it can be released along CToy executable. And libtcc1.a needs to be generated by tcc and also put at CToy's root (no rpath to handle there).
