### ISSUE TITLE
Can I opt to remove GLES window?

### ISSUE THREAD

**Issue by stevefan1999-personal** [anael-seghezzi/CToy#15]
I want to use CToy for learning algorithms, but it is very annoying to see a black screen that I never needs...

Also, I wish there could be Makefile support so we have can a live-reloading infrastructure in basically anywhere.

**Comment by anael-seghezzi** [comment]
I think in this case it would be better if you just use libtcc directly. Specially for learning where you want to compile a candidate when you want.
