### ISSUE TITLE
F*** you!

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [anael-seghezzi/CToy#16]
Why is this only available on 64-bit OS? I don't have any 64-bit PC at hand at the moment, so a port to 32-bit will make me happy. I have had enough with two other free fantasy consoles being only on 64-bit and not having a 32-bit release.

**Comment by carlsmith** [comment]
Buy a RPi?

**Comment by SamyBencherif** [comment]
@StinkerB06 hey homie, that’s not how we do things around here. Be nice
