### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by ryanford** [anael-seghezzi/CToy#18]
Any plans to make docs for the API?

**Comment by anael-seghezzi** [comment]
Not yet, but it's a good point, so I'll mark it as an improvement.

**Comment by nukeop** [comment]
I think this is preventing many people from taking a further interest in this project, it's hard (although possible) to figure out what's going on in the examples just from the code.

**Comment by carlsmith** [comment]
I'm a Web dev, looking to learn C. Having a tutorial that just shows us how to use the API would be really helpful for someone like me.

**Comment by carlsmith** [comment]
As someone who knows a few scripting languages, but nothing lower level, I was hoping to use CToy to get started with C programming, but the lack of docs makes it difficult to know where to begin. Taking an open source C intro, then tailoring it to CToy, would be helpful - just something to get up and running.

**Comment by triptych** [comment]
Creating something you expect others to use and develop on will require comprehensive documentation. Otherwise you have an audience of one

**Comment by anael-seghezzi** [comment]
I don't really expect anything actually, I have done my share of open-source pro bono. But, hey, you all got a point, so I took some time to write a bit of documentation in the README (Usage) https://github.com/anael-seghezzi/CToy and CToy.h (API) https://github.com/anael-seghezzi/CToy/blob/master/ressources/include/ctoy.h

**Comment by carlsmith** [comment]
Thank you. I found this repo a while back, but couldn't get into it till I saw this till today. I'm now up and running, learning C with K&R and CToy. Cheers.

**Comment by QuentinWidlocher** [comment]
I never used C before and thought CToy would be a nice way to experiment with it but the lack of documentation (mainly for MaratisTCL and how to simply display a picture) is preventing me from moving forward, I guess I cannot be the only one, since your tool is for learning purpose too ?

**Comment by anael-seghezzi** [comment]
It's quite straightforward but I have some idle time because of COVID so I'll write some tutorials in the wiki. Stay tuned.

**Comment by anael-seghezzi** [comment]
Here is a start: https://github.com/anael-seghezzi/CToy/wiki

**Comment by anael-seghezzi** [comment]
New, how to make a bomberman clone: https://github.com/anael-seghezzi/CToy/wiki/Making-a-little-Bomberman-clone
