### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [anael-seghezzi/CToy#2]
I would like to point out that identifiers like "[`_CTOY_H_`](https://github.com/anael-seghezzi/CToy/blob/17bbff6aa08fd7602a659460db3c6a329419e3f1/src/ctoy.h#L28)" and "[`_M_DIST_T`](https://github.com/anael-seghezzi/CToy/blob/b784eb312bb726e9fae6789f05e1eac175327798/src/m_dist.h#L88)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by anael-seghezzi** [comment]
You are right, it should be ok now

**Comment by elfring** [comment]
Thanks for [your improvement of affected identifiers](https://github.com/DaveDavenport/rofi/commit/8104997e6f1c2d9de4c9757d6cfa79831aa20e9c).

How do you think about support for [the programming language "C++"](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797)?

**Comment by anael-seghezzi** [comment]
Do you refer to the double underscore ? The code is written in pure C and maratis_tiny_c_lib make use of `extern "C"`. So C should take precedence.

**Comment by elfring** [comment]
I suggest to [reconsider also the use of double underscores](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations) in your source files.

Would you like to take the possibility into account that a developer would instruct an other compiler implementation to perform data processing with the provided files as C++ source code intentionally?
