### ISSUE TITLE
Consider replacing OpenAL by mini_al

### ISSUE THREAD

**Issue by raysan5** [anael-seghezzi/CToy#20]
My experience: after more than 4 years using OpenAL for raylib, just switched to [mini_al](https://github.com/dr-soft/mini_al) library. 

It's small, single-file header-only, multiplatform and removed the need of distributing `OpenAL32.dll` with your programs. I think it can make CToy a more self-contained product.

**Comment by anael-seghezzi** [comment]
Interesting, I'm using openal-soft on windows (but not yet on unix), it's quite good too and standard.
