### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by vulpivia** [anael-seghezzi/CToy#21]
I can't find any license information in this project. Would be nice to have a LICENSE file to know if people can contribute.

**Comment by anael-seghezzi** [comment]
The licenses are written inside the code files or folders, CToy is zlib/libpng, but the third-parties are various (but permissive).

**Comment by vulpivia** [comment]
Oh, I missed that. Maybe a license file would still be a good idea, so GitHub will display the license?
