### ISSUE TITLE
Missing VCOMP140.dll and VCRuntime140.dll 

### ISSUE THREAD

**Issue by ivan-cx** [anael-seghezzi/CToy#22]
On a freshly installed Windows 10, downloaded CToy-1.05-WIN-x86_64.zip
When I launch CToy.exe or CToy_player.exe it reports missing dlls from Microsoft Visual C++ 2015 Redistributable

Downloading and installing Redist solves the problem, so it's not a big issue.
https://www.microsoft.com/en-us/download/confirmation.aspx?id=52685

**Comment by anael-seghezzi** [comment]
Thank you, I'll add the link to the main page for now.
