### ISSUE TITLE
imgui_hello.c sample undefined symbol

### ISSUE THREAD

**Issue by blazer2k1** [anael-seghezzi/CToy#26]
I already placed the compiled `libcimgui.dll` and `libcimgui.dll.a` on the resources folder where ctoy.exe resides..

The rest of the samples works fine.

```
tcc: error: undefined symbol 'igGetIO'
tcc: error: undefined symbol 'ImGuiIO_AddInputCharacter'
tcc: error: undefined symbol 'ImFontAtlas_GetTexDataAsRGBA32'
tcc: error: undefined symbol 'igCreateContext'
tcc: error: undefined symbol 'igDestroyContext'
tcc: error: undefined symbol 'igNewFrame'
tcc: error: undefined symbol 'igText'
tcc: error: undefined symbol 'igButton'
tcc: error: undefined symbol 'igInputText'
tcc: error: undefined symbol 'igSliderFloat'
tcc: error: undefined symbol 'igRender'
tcc: error: undefined symbol 'igGetDrawData'
```

**Comment by anael-seghezzi** [comment]
What are you running exactly ? Did you download the binary or are you trying to build it yourself ?
Because if you are compiling on windows, with visual studio, just run the "INSTALL" target and it will copy the files.
Otherwise, the dll (not the .a) goes in the "lib/" folder next to ctoy.exe

**Comment by blazer2k1** [comment]
> Otherwise, the dll (not the .a) goes in the "lib/" folder next to ctoy.exe

this solved it, thanks.

just a small suggestion: perhaps creating an empty `lib` folder with a readme.txt would provide a better hint, also should be [**resources**](https://github.com/anael-seghezzi/CToy/tree/master/ressources) and not _ressources_, if this is not intentional.
