### ISSUE TITLE
`libtcc_hello` sample doesn't work as intended

### ISSUE THREAD

**Issue by NullDott** [anael-seghezzi/CToy#28]
When I try to run the fourth sample I get this output:

```
<sample libtcc_hello>
tcc: error: file '/usr/local/lib/tcc/x86-64/libtcc1.a' not found
```

It seems to be looking for `libtcc1.a` in the system path instead of using the `x86-64` folder located in the root directory, how can I solve this issue? Is this supposed to be the default behavior?

Creating the required route and moving the static library seems to make it work correctly, but this could become a problem when shipping a CToy program with that dependency, since it would not be able to find it there. 

**OS:** Linux Mint 21.3 (based in Ubuntu 22.04 LTS)

**Comment by anael-seghezzi** [comment]
This line should fix it -> https://github.com/anael-seghezzi/CToy/commit/6b468dd93e197c0d62e9064f72100c30e95092aa

**Comment by NullDott** [comment]
Thanks so much! It works now!!!
