### ISSUE TITLE
TCC alternatives, Apple Silicon

### ISSUE THREAD

**Issue by MuffinHop** [anael-seghezzi/CToy#29]
Hello!

Can see many potential use cases for CToy for myself and a hobbyist demoscene team I work with but unfortunately my main platform is an apple M1 which is an ARM platform, and I'd like to stick to this platform. Tcc has a lot of x86 dependencies built in and at least I myself have struggled to get tcc to work with the Rosetta 2 translation layer.

Is there any possibility of adding an alternative to tcc with some other c compiler or solve the issue in some other way?

Thanks for any tips or suggestions.

``` Build % make
[  6%] Built target tinycthread
[ 62%] Built target glfw
[ 65%] Linking C executable CToy
ld: warning: ignoring file '/CToy-master/3rdparty/libtcc/osx/libtcc.dylib': found architecture 'x86_64', required architecture 'arm64'```

**Comment by anael-seghezzi** [comment]
The latest version of TCC should be able to work on ARM, there is still work to do it seems but you can follow previous attempts at compiling on ARM here : https://github.com/anael-seghezzi/CToy/issues/19
