### ISSUE TITLE
vsync control / frame limiting

### ISSUE THREAD

**Issue by fo-fo** [anael-seghezzi/CToy#6]
Is there any way to control vsync and/or frame limiting? On my computer the hello_world example runs overly fast (at 100 % CPU core usage).

**Comment by anael-seghezzi** [comment]
Hi, it should be on by default except if defined as "always off" in your GPU driver setting.
I added a line to enforce v-sync on commit 7c81adf in case it helps. Let me know.

**Comment by fo-fo** [comment]
Yeah, looks like vsync is off by default on Intel GPU drivers on Windows. The `glfwSwapInterval` change is good enough for me, thanks!
