### ISSUE TITLE
Compiling on Linux, GLFW Question

### ISSUE THREAD

**Issue by Smilex** [anael-seghezzi/CToy#7]
Hey,

I've been working on getting this to work on my Linux machine and I had linker issues with the GLFW you had bundled with it. I replaced it with https://github.com/glfw/glfw, and I got past those issues.

Your GLFW directory has less stuff than the original. Is it because you got it from a fork, and if so could you give me a link? Or is it something you cleaned up yourself, in which case could you tell me what stuff I should cut out?

UPDATE: CToy is now compiling & running on my Linux machine

**Comment by anael-seghezzi** [comment]
Hi and thanks.

I think it's just that I used one of the first version of GLFW 3, I remember modifying the CMake file heavily but I don't remember why. Did you manage to include this new version within the current CToy CMake script ? If so, could you make it a pull request ? I can test it on mac & windows.

Did you manage to compile libtcc as a dynamic library without trouble ? (and could you include it in 3rdparty/libtcc/ ?)

Also, for linux, I started working on the libc headers, but some of it is untested and may be buggy (specially dirent.h and stat.h).

**Comment by Smilex** [comment]
I just ignored the dynamic library of libtcc. It does work, but I do not know the details of your software, so I guess there's some importance to it also being a shared library? If so, I can try to port it.

I'll make a pull request for the entire thing. I just wanted to know if I should cut down on GLFW first.

**Comment by anael-seghezzi** [comment]
It's better if libtcc is linked as a dynamic library to not force C-Toy binary to be GPL (otherwise Zlib). But it can be taken care of later, not a problem.

**Comment by anael-seghezzi** [comment]
I tested it on Windows 7, all good.
