### ISSUE TITLE
Help with CToy

### ISSUE THREAD

**Issue by Smilex** [anael-seghezzi/CToy#9]
Hey,

I'm uncertain if the Github issue tracker should be used like this, but it does seem the most convenient for me.

I'm writing some code with CToy that compiles C files, which it then runs. Similar to one of your samples. I'm getting the following errors about repetition, and I'm wondering if you recognise which part I'm missing?

`In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:845: error: 'stbi_failure_reason' defined twice... may be -fcommon is needed?

In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:876: error: 'stbi_image_free' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:944: error: 'stbi_load' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:968: error: 'stbi_load_from_memory' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:975: error: 'stbi_load_from_callbacks' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:996: error: 'stbi_loadf_from_memory' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1003: error: 'stbi_loadf_from_callbacks' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1011: error: 'stbi_loadf' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1035: error: 'stbi_is_hdr_from_memory' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1049: error: 'stbi_is_hdr' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1072: error: 'stbi_is_hdr_from_callbacks' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1086: error: 'stbi_ldr_to_hdr_gamma' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1087: error: 'stbi_ldr_to_hdr_scale' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1090: error: 'stbi_hdr_to_ldr_gamma' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:1091: error: 'stbi_hdr_to_ldr_scale' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:3708: error: 'stbi_zlib_decode_malloc_guesssize' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:3724: error: 'stbi_zlib_decode_malloc' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:3729: error: 'stbi_zlib_decode_malloc_guesssize_headerflag' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:3745: error: 'stbi_zlib_decode_buffer' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:3756: error: 'stbi_zlib_decode_noheader_malloc' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:3772: error: 'stbi_zlib_decode_noheader_buffer' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:4144: error: 'stbi_set_unpremultiply_on_load' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:4149: error: 'stbi_convert_iphone_png_to_rgb' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:6155: error: 'stbi_info' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:6177: error: 'stbi_info_from_memory' defined twice... may be -fcommon is needed?
In file included from /tmp/web_native/img_util.c:4:
/tmp/web_native/stb_image.h:6184: error: 'stbi_info_from_callbacks' defined twice... may be -fcommon is needed?
/tmp/web_native/img_util.c:7: error: 'm_image_load' defined twice... may be -fcommon is needed?
/tmp/web_native/img_util.c:16: warning: implicit declaration of function 'm_image_create'
/tmp/web_native/img_util.c:16: error: 'M_UBYTE' undeclared
`

**Comment by Smilex** [comment]
I added the files, and they were included in one of them. I don't know how to delete this, so I'll just close it.

**Comment by anael-seghezzi** [comment]
Hi, email is better, you can find it on my github account.
